
CREATE DATABASE IF NOT EXISTS `kayo_sql` /*!40100 DEFAULT CHARACTER SET latin1 */;
USE `kayo_sql`;

CREATE TABLE IF NOT EXISTS `staff_users` (
	`staffDiscord` VARCHAR(50) NOT NULL,
  	`servico` varchar(50) NOT NULL
)ENGINE=InnoDB DEFAULT CHARSET=UTF8;